name: flutter_modular_app
description: A Nero Lab Project created by Nero Lab CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auth:
    path: ./auth
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  get: ^4.6.1
  get_it: ^7.2.0
  sentry_flutter: ^6.2.2

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  device_preview: ^1.0.0
  flutter_driver:
    sdk: flutter
  flutter_native_splash: ^1.3.3
  flutter_sheet_localization_generator: ^5.1.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.3
  mockito: ^5.0.17
  mocktail: ^0.2.0
  network_image_mock: ^2.0.1
  very_good_analysis: ^2.4.0

dependency_overrides:
  analyzer: ^2.6.0
  meta: ^1.7.0
  provider: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
